# Generated by Django 4.1.7 on 2023-06-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tz_answer',
            name='name_tz',
            field=models.CharField(default=1, max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tz_answer',
            name='user',
            field=models.CharField(default=1, max_length=200, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
