# Generated by Django 4.1.7 on 2023-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tz_answer_name_tz_tz_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rez',
            name='ball',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
